//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doug.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public Nullable<int> WeightLifting { get; set; }
        public Nullable<int> Running { get; set; }
        public Nullable<int> Walking { get; set; }
        public Nullable<int> Other { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    }
}
