//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doug.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DPFitness_dbEntities : DbContext
    {
        public DPFitness_dbEntities()
            : base("name=DPFitness_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Diary> Diaries { get; set; }
        public virtual DbSet<Stat> Stats { get; set; }
        public virtual DbSet<test> tests { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
