//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doug.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stat
    {
        public int Id { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> BodyFat { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public string Username { get; set; }
    }
}
